apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: goodfood
spec:
  replicas: 1
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      serviceAccountName: app-sa
      containers:
        - name: gateway
          # image: your-registry/goodfood-gateway:latest
          image: goodfood-gateway:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8090, name: http }]
          env:
            - { name: SPRING_PROFILES_ACTIVE, value: "docker" }
            # - { name: SPRING_CONFIG_IMPORT, valueFrom: { configMapKeyRef: { name: goodfood-config, key: CONFIG_SERVER_URL } } }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8090 }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8090 }
            initialDelaySeconds: 20
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "800m", memory: "768Mi" }
