server:
  port: 8082
  
spring:
  application:
    name: goodfood-order-service
          
  kafka:
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
