apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: goodfood
spec:
  replicas: 1
  selector: { matchLabels: { app: auth-server } }
  template:
    metadata: { labels: { app: auth-server } }
    spec:
      serviceAccountName: app-sa
      terminationGracePeriodSeconds: 30
      containers:
        - name: auth-server
          image: goodfood-auth-server:latest          
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 9000, name: http }]
          env:
            - { name: SPRING_PROFILES_ACTIVE, value: "docker" }
            # - { name: SPRING_CONFIG_IMPORT, valueFrom: { configMapKeyRef: { name: goodfood-config, key: CONFIG_SERVER_URL } } }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 9000 }
            initialDelaySeconds: 15
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 9000 }
            initialDelaySeconds: 25
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "800m", memory: "1Gi" }
          # securityContext:
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: false
