spring:
  config:
    import: configserver:http://config-server:8888

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-server:9000
          predicates:
            - Path=/auth/**,/oauth2/**,/actuator/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/payments/**
        - id: restaurant-service
          uri: http://restaurant-service:8084
          predicates:
            - Path=/restaurants/**
        - id: delivery-service
          uri: http://delivery-service:8085
          predicates:
            - Path=/deliveries/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
