apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: goodfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: goodfood-auth-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_PASSWORD
              value: 

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: goodfood
spec:
  selector:
    app: auth-server
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
