apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: goodfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: goodfood-delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: goodfood
spec:
  selector:
    app: delivery-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
