apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: goodfood
spec:
  replicas: 1
  strategy:
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  selector: { matchLabels: { app: delivery-service } }
  template:
    metadata:
      labels: { app: delivery-service }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8085"
    spec:
      serviceAccountName: app-sa
      terminationGracePeriodSeconds: 30
      containers:
        - name: delivery-service
          image: goodfood-delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8085, name: http }]
          env:
            - { name: SPRING_PROFILES_ACTIVE, value: "k8s" }
            - { name: SPRING_CONFIG_IMPORT, valueFrom: { configMapKeyRef: { name: goodfood-config, key: CONFIG_SERVER_URL } } }
            - { name: DB_PASSWORD, valueFrom: { secretKeyRef: { name: goodfood-secrets, key: mysql-root-password } } }
            # - { name: JAVA_TOOL_OPTIONS, value: "-XX:MaxRAMPercentage=75 -XX:+UseG1GC -Dsun.net.inetaddr.ttl=30" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8085 }
            initialDelaySeconds: 12
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8085 }
            initialDelaySeconds: 25
            periodSeconds: 20
          resources:
            requests: { cpu: "200m", memory: "256Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
