spring:
  application:
    name: auth-server

  config:
    import: "optional:configserver:http://config-server:8888"


# Put plain client secret here (it will be encoded at startup)
client:
  id: "gateway-client"
  secret: "gateway-secret"