apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: goodfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 654129064103.dkr.ecr.ap-south-1.amazonaws.com/goodfood-order-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: aws
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server.goodfood.svc.cluster.local:8888"
            # - name: AUTH_SERVICE_URL
            #   value: "http://auth-server.goodfood.svc.cluster.local:9000"
            - name: AUTH_SERVER_IP
              value: "http://auth-server.goodfood.svc.cluster.local:9000"
            # - name: KAFKA_BOOTSTRAP_SERVERS
            #   value: ":9092"
            - name: BOOTSTRAP_SERVER_IP
              value: ""
            - name: DB_HOST
              value: 
            - name: DB_NAME
              value: authdb
            - name: DB_USER
              value: 
            - name: DB_PASSWORD
              value: 
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
